# Generated by Django 3.2.12 on 2022-04-03 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_completed_booking', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('province', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('ward', models.CharField(blank=True, max_length=128, null=True)),
                ('hamlet', models.CharField(blank=True, max_length=128, null=True)),
                ('street', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.baseuser')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.baseuser',),
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.baseuser')),
                ('salon_name', models.CharField(max_length=255, unique=True)),
                ('background_image', models.CharField(blank=True, max_length=256, null=True)),
                ('vote_rate', models.FloatField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('addresses', models.ManyToManyField(blank=True, related_name='user_addresses', to='account.Address')),
                ('address', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.baseuser',),
        ),
    ]
