# Generated by Django 3.2.12 on 2022-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220403_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Vĩ độ', null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Kinh độ', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, help_text='Địa chỉ cụ thể', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='alias',
            field=models.CharField(blank=True, help_text='Bí danh. Có thể là tên,...', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(help_text='Quận/huyện', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='hamlet',
            field=models.CharField(blank=True, help_text='Thôn/xóm/ấp', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(help_text='Tỉnh', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, help_text='Đường', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.CharField(blank=True, help_text='Phường/xã', max_length=128, null=True),
        ),
    ]
