# Generated by Django 3.2.12 on 2022-04-14 16:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220403_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='addresses',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_salon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
