# Generated by Django 3.2.12 on 2022-04-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220422_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='Thành phố', max_length=128, null=True),
        ),
    ]
