# Generated by Django 3.2.12 on 2022-04-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220423_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, help_text='Tỉnh', max_length=128, null=True),
        ),
    ]
