# Generated by Django 3.2.12 on 2022-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='address',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(help_text='Quận/huyện/thành phố không trực thuộc', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='hamlet',
            field=models.CharField(blank=True, help_text='Thôn/xóm/ấp/đường', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, help_text='Tỉnh/thành phố trực thuộc', max_length=128, null=True),
        ),
    ]
