# Generated by Django 3.2.12 on 2022-06-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_baseuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='avatar',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
