# Generated by Django 3.2.12 on 2022-06-19 03:43

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_baseuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='private_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
