# Generated by Django 3.2.12 on 2022-06-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20220619_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
