# Generated by Django 3.2.12 on 2022-06-20 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcatNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('verb', models.CharField(choices=[('booking_placed', 'Booking Placed'), ('booking_confirmed', 'Booking Confirmed'), ('booking_canceled', 'Booking Canceled'), ('booking_requested_to_complete', 'Booking Requested To Complete'), ('booking_completed', 'Booking Completed')], max_length=255)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concat_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
