# Generated by Django 3.2.12 on 2022-05-29 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0017_auto_20220511_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=32)),
                ('total_net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
