# Generated by Django 3.2.12 on 2022-05-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('cancel', 'Cancel'), ('completed', 'Completed')], default='new', max_length=32),
        ),
    ]
