# Generated by Django 3.2.12 on 2022-05-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_name'),
        ('booking', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_services', to='service.service'),
        ),
    ]
