# Generated by Django 3.2.12 on 2022-06-13 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20220529_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('request_to_complete', 'Request To Complete'), ('completed', 'Completed')], default='new', max_length=32),
        ),
    ]
