# Generated by Django 3.2.12 on 2022-05-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20220511_1649'),
        ('service', '0005_auto_20220511_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesalon',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='account.salon'),
        ),
    ]
